
## codes to be used with fontawesome
## this object is not exported

codeawesome <- structure(
  c("f000", "f001", "f002", "f003", "f004", "f005", "f006", "f007", "f008",
    "f009", "f00a", "f00b", "f00c", "f00d", "f00e", "f010", "f011", "f012",
    "f013", "f014", "f015", "f016", "f017", "f018", "f019", "f01a", "f01b",
    "f01c", "f01d", "f01e", "f021", "f022", "f023", "f024", "f025", "f026",
    "f027", "f028", "f029", "f02a", "f02b", "f02c", "f02d", "f02e", "f02f",
    "f030", "f031", "f032", "f033", "f034", "f035", "f036", "f037", "f038",
    "f039", "f03a", "f03b", "f03c", "f03d", "f03e", "f040", "f041", "f042",
    "f043", "f044", "f045", "f046", "f047", "f048", "f049", "f04a", "f04b",
    "f04c", "f04d", "f04e", "f050", "f051", "f052", "f053", "f054", "f055",
    "f056", "f057", "f058", "f059", "f05a", "f05b", "f05c", "f05d", "f05e",
    "f060", "f061", "f062", "f063", "f064", "f065", "f066", "f067", "f068",
    "f069", "f06a", "f06b", "f06c", "f06d", "f06e", "f070", "f071", "f072",
    "f073", "f074", "f075", "f076", "f077", "f078", "f079", "f07a", "f07b",
    "f07c", "f07d", "f07e", "f080", "f081", "f082", "f083", "f084", "f085",
    "f086", "f087", "f088", "f089", "f08a", "f08b", "f08c", "f08d", "f08e",
    "f090", "f091", "f092", "f093", "f094", "f095", "f096", "f097", "f098",
    "f099", "f09a", "f09b", "f09c", "f09d", "f09e", "f0a0", "f0a1", "f0f3",
    "f0a3", "f0a4", "f0a5", "f0a6", "f0a7", "f0a8", "f0a9", "f0aa", "f0ab",
    "f0ac", "f0ad", "f0ae", "f0b0", "f0b1", "f0b2", "f0c0", "f0c1", "f0c2",
    "f0c3", "f0c4", "f0c5", "f0c6", "f0c7", "f0c8", "f0c9", "f0ca", "f0cb",
    "f0cc", "f0cd", "f0ce", "f0d0", "f0d1", "f0d2", "f0d3", "f0d4", "f0d5",
    "f0d6", "f0d7", "f0d8", "f0d9", "f0da", "f0db", "f0dc", "f0dd", "f0de",
    "f0e0", "f0e1", "f0e2", "f0e3", "f0e4", "f0e5", "f0e6", "f0e7", "f0e8",
    "f0e9", "f0ea", "f0eb", "f0ec", "f0ed", "f0ee", "f0f0", "f0f1", "f0f2",
    "f0a2", "f0f4", "f0f5", "f0f6", "f0f7", "f0f8", "f0f9", "f0fa", "f0fb",
    "f0fc", "f0fd", "f0fe", "f100", "f101", "f102", "f103", "f104", "f105",
    "f106", "f107", "f108", "f109", "f10a", "f10b", "f10c", "f10d", "f10e",
    "f110", "f111", "f112", "f113", "f114", "f115", "f118", "f119", "f11a",
    "f11b", "f11c", "f11d", "f11e", "f120", "f121", "f122", "f123", "f124",
    "f125", "f126", "f127", "f128", "f129", "f12a", "f12b", "f12c", "f12d",
    "f12e", "f130", "f131", "f132", "f133", "f134", "f135", "f136", "f137",
    "f138", "f139", "f13a", "f13b", "f13c", "f13d", "f13e", "f140", "f141",
    "f142", "f143", "f144", "f145", "f146", "f147", "f148", "f149", "f14a",
    "f14b", "f14c", "f14d", "f14e", "f150", "f151", "f152", "f153", "f154",
    "f155", "f156", "f157", "f158", "f159", "f15a", "f15b", "f15c", "f15d",
    "f15e", "f160", "f161", "f162", "f163", "f164", "f165", "f166", "f167",
    "f168", "f169", "f16a", "f16b", "f16c", "f16d", "f16e", "f170", "f171",
    "f172", "f173", "f174", "f175", "f176", "f177", "f178", "f179", "f17a",
    "f17b", "f17c", "f17d", "f17e", "f180", "f181", "f182", "f183", "f184",
    "f185", "f186", "f187", "f188", "f189", "f18a", "f18b", "f18c", "f18d",
    "f18e", "f190", "f191", "f192", "f193", "f194", "f195", "f196", "f197",
    "f198", "f199", "f19a", "f19b", "f19c", "f19d", "f19e", "f1a0", "f1a1",
    "f1a2", "f1a3", "f1a4", "f1a5", "f1a6", "f1a7", "f1a8", "f1a9", "f1aa",
    "f1ab", "f1ac", "f1ad", "f1ae", "f1b0", "f1b1", "f1b2", "f1b3", "f1b4",
    "f1b5", "f1b6", "f1b7", "f1b8", "f1b9", "f1ba", "f1bb", "f1bc", "f1bd",
    "f1be", "f1c0", "f1c1", "f1c2", "f1c3", "f1c4", "f1c5", "f1c6", "f1c7",
    "f1c8", "f1c9", "f1ca", "f1cb", "f1cc", "f1cd", "f1ce", "f1d0", "f1d1",
    "f1d2", "f1d3", "f1d4", "f1d5", "f1d6", "f1d7", "f1d8", "f1d9", "f1da",
    "f1db", "f1dc", "f1dd", "f1de", "f1e0", "f1e1", "f1e2", "f1e3", "f1e4",
    "f1e5", "f1e6", "f1e7", "f1e8", "f1e9", "f1ea", "f1eb", "f1ec", "f1ed",
    "f1ee", "f1f0", "f1f1", "f1f2", "f1f3", "f1f4", "f1f5", "f1f6", "f1f7",
    "f1f8", "f1f9", "f1fa", "f1fb", "f1fc", "f1fd", "f1fe", "f200", "f201",
    "f202", "f203", "f204", "f205", "f206", "f207", "f208", "f209", "f20a",
    "f20b", "f20c", "f20d", "f20e", "f210", "f211", "f212", "f213", "f214",
    "f215", "f216", "f217", "f218", "f219", "f21a", "f21b", "f21c", "f21d",
    "f21e", "f221", "f222", "f223", "f224", "f225", "f226", "f227", "f228",
    "f229", "f22a", "f22b", "f22c", "f230", "f231", "f232", "f233", "f234",
    "f235", "f236", "f237", "f238", "f239", "f23a"), .Names = c("fa-glass",
    "fa-music", "fa-search", "fa-envelope-o", "fa-heart", "fa-star",
    "fa-star-o", "fa-user", "fa-film", "fa-th-large", "fa-th", "fa-th-list",
    "fa-check", "fa-times", "fa-search-plus", "fa-search-minus", "fa-power-off",
    "fa-signal", "fa-cog", "fa-trash-o", "fa-home", "fa-file-o", "fa-clock-o",
    "fa-road", "fa-download", "fa-arrow-circle-o-down", "fa-arrow-circle-o-up",
    "fa-inbox", "fa-play-circle-o", "fa-repeat", "fa-refresh", "fa-list-alt",
    "fa-lock", "fa-flag", "fa-headphones", "fa-volume-off", "fa-volume-down",
    "fa-volume-up", "fa-qrcode", "fa-barcode", "fa-tag", "fa-tags", "fa-book",
    "fa-bookmark", "fa-print", "fa-camera", "fa-font", "fa-bold", "fa-italic",
    "fa-text-height", "fa-text-width", "fa-align-left", "fa-align-center",
    "fa-align-right", "fa-align-justify", "fa-list", "fa-outdent", "fa-indent",
    "fa-video-camera", "fa-picture-o", "fa-pencil", "fa-map-marker",
    "fa-adjust", "fa-tint", "fa-pencil-square-o", "fa-share-square-o",
    "fa-check-square-o", "fa-arrows", "fa-step-backward", "fa-fast-backward",
    "fa-backward", "fa-play", "fa-pause", "fa-stop", "fa-forward",
    "fa-fast-forward", "fa-step-forward", "fa-eject", "fa-chevron-left",
    "fa-chevron-right", "fa-plus-circle", "fa-minus-circle", "fa-times-circle",
    "fa-check-circle", "fa-question-circle", "fa-info-circle", "fa-crosshairs",
    "fa-times-circle-o", "fa-check-circle-o", "fa-ban", "fa-arrow-left",
    "fa-arrow-right", "fa-arrow-up", "fa-arrow-down", "fa-share", "fa-expand",
    "fa-compress", "fa-plus", "fa-minus", "fa-asterisk",
    "fa-exclamation-circle", "fa-gift", "fa-leaf", "fa-fire", "fa-eye",
    "fa-eye-slash", "fa-exclamation-triangle", "fa-plane", "fa-calendar",
    "fa-random", "fa-comment", "fa-magnet", "fa-chevron-up", "fa-chevron-down",
    "fa-retweet", "fa-shopping-cart", "fa-folder", "fa-folder-open",
    "fa-arrows-v", "fa-arrows-h", "fa-bar-chart", "fa-twitter-square",
    "fa-facebook-square", "fa-camera-retro", "fa-key", "fa-cogs", "fa-comments",
    "fa-thumbs-o-up", "fa-thumbs-o-down", "fa-star-half", "fa-heart-o",
    "fa-sign-out", "fa-linkedin-square", "fa-thumb-tack", "fa-external-link",
    "fa-sign-in", "fa-trophy", "fa-github-square", "fa-upload", "fa-lemon-o",
    "fa-phone", "fa-square-o", "fa-bookmark-o", "fa-phone-square", "fa-twitter",
    "fa-facebook", "fa-github", "fa-unlock", "fa-credit-card", "fa-rss",
    "fa-hdd-o", "fa-bullhorn", "fa-bell", "fa-certificate", "fa-hand-o-right",
    "fa-hand-o-left", "fa-hand-o-up", "fa-hand-o-down", "fa-arrow-circle-left",
    "fa-arrow-circle-right", "fa-arrow-circle-up", "fa-arrow-circle-down",
    "fa-globe", "fa-wrench", "fa-tasks", "fa-filter", "fa-briefcase",
    "fa-arrows-alt", "fa-users", "fa-link", "fa-cloud", "fa-flask",
    "fa-scissors", "fa-files-o", "fa-paperclip", "fa-floppy-o", "fa-square",
    "fa-bars", "fa-list-ul", "fa-list-ol", "fa-strikethrough", "fa-underline",
    "fa-table", "fa-magic", "fa-truck", "fa-pinterest", "fa-pinterest-square",
    "fa-google-plus-square", "fa-google-plus", "fa-money", "fa-caret-down",
    "fa-caret-up", "fa-caret-left", "fa-caret-right", "fa-columns", "fa-sort",
    "fa-sort-desc", "fa-sort-asc", "fa-envelope", "fa-linkedin", "fa-undo",
    "fa-gavel", "fa-tachometer", "fa-comment-o", "fa-comments-o", "fa-bolt",
    "fa-sitemap", "fa-umbrella", "fa-clipboard", "fa-lightbulb-o",
    "fa-exchange", "fa-cloud-download", "fa-cloud-upload", "fa-user-md",
    "fa-stethoscope", "fa-suitcase", "fa-bell-o", "fa-coffee", "fa-cutlery",
    "fa-file-text-o", "fa-building-o", "fa-hospital-o", "fa-ambulance",
    "fa-medkit", "fa-fighter-jet", "fa-beer", "fa-h-square", "fa-plus-square",
    "fa-angle-double-left", "fa-angle-double-right", "fa-angle-double-up",
    "fa-angle-double-down", "fa-angle-left", "fa-angle-right", "fa-angle-up",
    "fa-angle-down", "fa-desktop", "fa-laptop", "fa-tablet", "fa-mobile",
    "fa-circle-o", "fa-quote-left", "fa-quote-right", "fa-spinner", "fa-circle",
    "fa-reply", "fa-github-alt", "fa-folder-o", "fa-folder-open-o",
    "fa-smile-o", "fa-frown-o", "fa-meh-o", "fa-gamepad", "fa-keyboard-o",
    "fa-flag-o", "fa-flag-checkered", "fa-terminal", "fa-code", "fa-reply-all",
    "fa-star-half-o", "fa-location-arrow", "fa-crop", "fa-code-fork",
    "fa-chain-broken", "fa-question", "fa-info", "fa-exclamation",
    "fa-superscript", "fa-subscript", "fa-eraser", "fa-puzzle-piece",
    "fa-microphone", "fa-microphone-slash", "fa-shield", "fa-calendar-o",
    "fa-fire-extinguisher", "fa-rocket", "fa-maxcdn", "fa-chevron-circle-left",
    "fa-chevron-circle-right", "fa-chevron-circle-up", "fa-chevron-circle-down",
    "fa-html5", "fa-css3", "fa-anchor", "fa-unlock-alt", "fa-bullseye",
    "fa-ellipsis-h", "fa-ellipsis-v", "fa-rss-square", "fa-play-circle",
    "fa-ticket", "fa-minus-square", "fa-minus-square-o", "fa-level-up",
    "fa-level-down", "fa-check-square", "fa-pencil-square",
    "fa-external-link-square", "fa-share-square", "fa-compass",
    "fa-caret-square-o-down", "fa-caret-square-o-up", "fa-caret-square-o-right",
    "fa-eur", "fa-gbp", "fa-usd", "fa-inr", "fa-jpy", "fa-rub", "fa-krw",
    "fa-btc", "fa-file", "fa-file-text", "fa-sort-alpha-asc",
    "fa-sort-alpha-desc", "fa-sort-amount-asc", "fa-sort-amount-desc",
    "fa-sort-numeric-asc", "fa-sort-numeric-desc", "fa-thumbs-up",
    "fa-thumbs-down", "fa-youtube-square", "fa-youtube", "fa-xing",
    "fa-xing-square", "fa-youtube-play", "fa-dropbox", "fa-stack-overflow",
    "fa-instagram", "fa-flickr", "fa-adn", "fa-bitbucket",
    "fa-bitbucket-square", "fa-tumblr", "fa-tumblr-square",
    "fa-long-arrow-down", "fa-long-arrow-up", "fa-long-arrow-left",
    "fa-long-arrow-right", "fa-apple", "fa-windows", "fa-android", "fa-linux",
    "fa-dribbble", "fa-skype", "fa-foursquare", "fa-trello", "fa-female",
    "fa-male", "fa-gratipay", "fa-sun-o", "fa-moon-o", "fa-archive", "fa-bug",
    "fa-vk", "fa-weibo", "fa-renren", "fa-pagelines", "fa-stack-exchange",
    "fa-arrow-circle-o-right", "fa-arrow-circle-o-left",
    "fa-caret-square-o-left", "fa-dot-circle-o", "fa-wheelchair",
    "fa-vimeo-square", "fa-try", "fa-plus-square-o", "fa-space-shuttle",
    "fa-slack", "fa-envelope-square", "fa-wordpress", "fa-openid",
    "fa-university", "fa-graduation-cap", "fa-yahoo", "fa-google", "fa-reddit",
    "fa-reddit-square", "fa-stumbleupon-circle", "fa-stumbleupon",
    "fa-delicious", "fa-digg", "fa-pied-piper", "fa-pied-piper-alt",
    "fa-drupal", "fa-joomla", "fa-language", "fa-fax", "fa-building",
    "fa-child", "fa-paw", "fa-spoon", "fa-cube", "fa-cubes", "fa-behance",
    "fa-behance-square", "fa-steam", "fa-steam-square", "fa-recycle", "fa-car",
    "fa-taxi", "fa-tree", "fa-spotify", "fa-deviantart", "fa-soundcloud",
    "fa-database", "fa-file-pdf-o", "fa-file-word-o", "fa-file-excel-o",
    "fa-file-powerpoint-o", "fa-file-image-o", "fa-file-archive-o",
    "fa-file-audio-o", "fa-file-video-o", "fa-file-code-o", "fa-vine",
    "fa-codepen", "fa-jsfiddle", "fa-life-ring", "fa-circle-o-notch",
    "fa-rebel", "fa-empire", "fa-git-square", "fa-git", "fa-hacker-news",
    "fa-tencent-weibo", "fa-qq", "fa-weixin", "fa-paper-plane",
    "fa-paper-plane-o", "fa-history", "fa-circle-thin", "fa-header",
    "fa-paragraph", "fa-sliders", "fa-share-alt", "fa-share-alt-square",
    "fa-bomb", "fa-futbol-o", "fa-tty", "fa-binoculars", "fa-plug",
    "fa-slideshare", "fa-twitch", "fa-yelp", "fa-newspaper-o", "fa-wifi",
    "fa-calculator", "fa-paypal", "fa-google-wallet", "fa-cc-visa",
    "fa-cc-mastercard", "fa-cc-discover", "fa-cc-amex", "fa-cc-paypal",
    "fa-cc-stripe", "fa-bell-slash", "fa-bell-slash-o", "fa-trash",
    "fa-copyright", "fa-at", "fa-eyedropper", "fa-paint-brush",
    "fa-birthday-cake", "fa-area-chart", "fa-pie-chart", "fa-line-chart",
    "fa-lastfm", "fa-lastfm-square", "fa-toggle-off", "fa-toggle-on",
    "fa-bicycle", "fa-bus", "fa-ioxhost", "fa-angellist", "fa-cc", "fa-ils",
    "fa-meanpath", "fa-buysellads", "fa-connectdevelop", "fa-dashcube",
    "fa-forumbee", "fa-leanpub", "fa-sellsy", "fa-shirtsinbulk",
    "fa-simplybuilt", "fa-skyatlas", "fa-cart-plus", "fa-cart-arrow-down",
    "fa-diamond", "fa-ship", "fa-user-secret", "fa-motorcycle",
    "fa-street-view", "fa-heartbeat", "fa-venus", "fa-mars", "fa-mercury",
    "fa-transgender", "fa-transgender-alt", "fa-venus-double", "fa-mars-double",
    "fa-venus-mars", "fa-mars-stroke", "fa-mars-stroke-v", "fa-mars-stroke-h",
    "fa-neuter", "fa-facebook-official", "fa-pinterest-p", "fa-whatsapp",
    "fa-server", "fa-user-plus", "fa-user-times", "fa-bed", "fa-viacoin",
    "fa-train", "fa-subway", "fa-medium"))
